### ISSUE TITLE
Address review feedback

### ISSUE THREAD

**Issue by phentos** [tritonhacks/Tritonhack2024-ML-Starter-Kit#26]

**Comment by deeg-p23** [comment]
Minor feedback from the GameDev Kit team:
- [x] Point to the index.md in the README so students know where to start the setup process.
- [x] Maybe drop a few documentation links at important steps, i.e. relevant modules for NumPy, Pandas, Matplotlib, sklearn so that students can follow through with the learning process with a bit more depth if they'd prefer.

Other than that, everything looks great! The kit looks like a great start with ML.

**Comment by sunwoo604** [comment]
Completed
